### ISSUE TITLE
[1.21] The game crashes when using the last arrow of an arrow item stack in an equipped Quiver

### ISSUE THREAD

**Issue by pnk2u** [SolipIngen/minecraft.progressivearchery#66]
This is the crash report:

```
Description: Saving entity NBT

java.lang.IllegalStateException: Value must be within range [1;99]: 0; Item must not be minecraft:air
	at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287)
	at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81)
	at net.minecraft.item.ItemStack.encode(ItemStack.java:396)
	at net.minecraft.entity.player.PlayerInventory.writeNbt(PlayerInventory.java:415)
	at net.minecraft.entity.player.PlayerEntity.writeCustomDataToNbt(PlayerEntity.java:895)
	at net.minecraft.server.network.ServerPlayerEntity.writeCustomDataToNbt(ServerPlayerEntity.java:412)
	at net.minecraft.entity.Entity.writeNbt(Entity.java:1922)
	at net.minecraft.server.integrated.IntegratedPlayerManager.savePlayerData(IntegratedPlayerManager.java:28)
	at net.minecraft.server.PlayerManager.remove(PlayerManager.java:383)
	at net.minecraft.server.network.ServerPlayNetworkHandler.cleanUp(ServerPlayNetworkHandler.java:1250)
	at net.minecraft.server.network.ServerPlayNetworkHandler.onDisconnected(ServerPlayNetworkHandler.java:1239)
	at net.minecraft.network.ClientConnection.handleDisconnection(ClientConnection.java:673)
	at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo.java:189)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:1032)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:912)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:114)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by pnk2u** [comment]
The latest commit (version 1.2.0.b-1.21) fixes this issue on my end. (:

**Comment by SolipIngen** [comment]
Thank you for reporting the issue, and for checking the solution for yourself.

v1.2.0.b-1.21 has been published, and should resolve this issue. If no further updates are given in 24 hours, I will close this Issue.
