### ISSUE TITLE
1.21Fabric cannot connection Servers(not install fabric) bug

### ISSUE THREAD

**Issue by 1515393384** [SolipIngen/minecraft.progressivearchery#74]
### version: 1.21(Fabric)
Mods list:
 -fabric-api-0.100.7+1.21.jar
 -modmenu-11.0.1.jar
 -progressivearchery-1.2.0.c-1.21.jar
### Server：(no fabirc) or (inst fabric) ALL report  the
![1](https://github.com/user-attachments/assets/bc210d78-e959-47ff-8b18-86d530684d5a)
![3](https://github.com/user-attachments/assets/38a1d90a-3de5-46bd-833c-88d8c411137e)

### report tet:
---- Minecraft Network Protocol Error Report ----
// Don't worry, I'll be fine

Time: 2024-07-22 02:24:42
Description: Packet handling error

java.lang.IllegalStateException: Invalid entity data item type for field 15 on entity class_1548['Creeper'/28, l='ClientLevel', x=31.50, y=41.00, z=-45.50]: old=0(class java.lang.Integer), new=2(class java.lang.Byte)
	at net.minecraft.class_2945.method_12785(class_2945.java:126)
	at net.minecraft.class_2945.method_12779(class_2945.java:117)
	at net.minecraft.class_634.method_11093(class_634.java:553)
	at net.minecraft.class_2739.method_11808(class_2739.java:54)
	at net.minecraft.class_2739.method_11054(class_2739.java:12)
	at net.minecraft.class_634.method_48294(class_634.java:2203)
	at net.minecraft.class_8042.method_48329(class_8042.java:19)
	at net.minecraft.class_8042.method_11054(class_8042.java:7)
	at net.minecraft.class_2600.method_11072(class_2600.java:27)
	at net.minecraft.class_1255.method_18859(class_1255.java:162)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:136)
	at net.minecraft.class_1255.method_5383(class_1255.java:121)
	at net.minecraft.class_310.method_1523(class_310.java:1240)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2945.method_12785(class_2945.java:126)
	at net.minecraft.class_2945.method_12779(class_2945.java:117)
	at net.minecraft.class_634.method_11093(class_634.java:553)
	at net.minecraft.class_2739.method_11808(class_2739.java:54)
	at net.minecraft.class_2739.method_11054(class_2739.java:12)

-- Incoming Packet --
Details:
	Type: clientbound/minecraft:bundle
	Is Terminal: false
	Is Skippable: false
Stacktrace:
	at net.minecraft.class_2600.method_59803(class_2600.java:56)
	at net.minecraft.class_8673.method_60882(class_8673.java:136)
	at net.minecraft.class_8673.method_59807(class_8673.java:113)
	at net.minecraft.class_2600.method_11072(class_2600.java:32)
	at net.minecraft.class_1255.method_18859(class_1255.java:162)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:136)
	at net.minecraft.class_1255.method_5383(class_1255.java:121)
	at net.minecraft.class_310.method_1523(class_310.java:1240)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

-- Connection --
Details:
	Protocol: play
	Flow: CLIENTBOUND
	Server type: OTHER
	Server brand: vanilla

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 22.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 412564384 bytes (393 MiB) / 1103101952 bytes (1052 MiB) up to 7302283264 bytes (6964 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 7735HS with Radeon Graphics        
	Identifier: AuthenticAMD Family 25 Model 68 Stepping 1
	Microarchitecture: Zen 3
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MiB): 4096.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.11029.1008
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 5.60
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MiB): 16384.00
	Memory slot #1 clockSpeed (GHz): 5.60
	Memory slot #1 type: Unknown
	Virtual memory max (MiB): 33816.88
	Virtual memory used (MiB): 8368.75
	Swap memory total (MiB): 5425.86
	Swap memory used (MiB): 124.87
	Space in storage for jna.tmpdir (MiB): available: 131438.94, total: 160481.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 131438.94, total: 160481.00
	Space in storage for io.netty.native.workdir (MiB): available: 131438.94, total: 160481.00
	Space in storage for java.io.tmpdir (MiB): available: 131438.94, total: 160481.00
	Space in storage for workdir (MiB): available: 131438.94, total: 160481.00
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn1044m -Xmx6963m
	Fabric Mods: 
		fabric-api: Fabric API 0.100.7+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8cd1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.67+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.15+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.18+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.4.2+c111832ad1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.25+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.12+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f883d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.3+78017270d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.11+8f3583aed1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.13+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.1+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.0+ab7edbacd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.13+d1321076d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.10+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.25+5bd9f1bcd1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.3.0+0ae0b97dd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.5+48fb1586d1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f344d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.2.0+7e687b32d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.82+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.15+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8cd1
		fabricloader: Fabric Loader 0.16.0
			mixinextras: MixinExtras 0.4.0
		java: Java HotSpot(TM) 64-Bit Server VM 22
		minecraft: Minecraft 1.21
		modmenu: Mod Menu 11.0.1
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		progressivearchery: Progressive Archery 1.2.0.c-1.21

**Comment by 1515393384** [comment]
The problem has been identified, possibly due to the server not installing 'polymer bundle', so it is unclear. Once installed, it will be resolved

**Comment by SolipIngen** [comment]
Hello, thank you for writing in.

Has this issue been solved? If so, feel free to close this thread. I will close it myself if I do not hear back by this weekend.
